<a href="https://colab.research.google.com/github/Shivams9/DATA-SCIENCE/blob/main/starting_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating Numpy Arrays**

[Numpy Array documentation](https://numpy.org/doc/stable/reference/arrays.html)


Imports

In [ ]:

import numpy as np

Create an array using list

In [18]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Create an array using tuple

In [19]:
a = np.array((1, 2, 3, 4, 5))
print(a)

[1 2 3 4 5]


Create an array using set

In [23]:
a = np.array({1,2,3,4,5})
print(a)
print(type(a))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


Create an array using dictionary

In [22]:
a = np.array({"one":1,"two":2,"three":3,"four":4,"five":5})
print(a)
print(type(a))


{'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5}
<class 'numpy.ndarray'>


Create an array using range

In [ ]:
a = np.array(range(1,6))
print(a)


[1 2 3 4 5]


Create an array using ones

In [ ]:
a = np.ones(5)
print(a)


[1. 1. 1. 1. 1.]


Create an array using zeros

In [ ]:
a = np.zeros(5)
print(a)


[0. 0. 0. 0. 0.]


Create an array using arange

In [17]:
for i in range(0,6,1):
  print(i, end=' ')

for i in range(1,6):
  print(i, end=',')

a = np.array({1,3,5,7})
print(a)
print(type(a))

0 1 2 3 4 5 1,2,3,4,5,

NameError: ignored

In [ ]:
a = np.arange(5)
print(a)
a = np.arange(1,6)
print(a)
a = np.arange(1,6,2)
print(a)
a = np.arange(5,0,-1)
print(a)


[0 1 2 3 4]
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]


Create an array using random

In [ ]:
a = np.random.rand(1,10)
print(a)

a =np.random.power(5, 5)
print(a)

a =np.random.randint(5,size= 5)
print(a)

rng = np.random.default_rng()
a =rng.integers(5,size=5)
print(a)


[[0.65248831 0.82752473 0.55389144 0.12844286 0.4397348  0.20163512
  0.75449147 0.18745912 0.50693007 0.15693976]]
[0.70958735 0.95400815 0.86353282 0.92170734 0.80248319]
[1 2 1 3 3]
[1 4 0 3 4]
